name: Publish GTFS feed
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          zip -jr nelson-streetcar-gtfs.zip data
      - uses: npaun/md-gtfs-validator-action@master
        with:
          gtfs_path: nelson-streetcar-gtfs.zip
