name: Publish GTFS feed
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  GTFS_PATH: nelson-streetcar-gtfs.zip
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          zip -jr $GTFS_PATH data
      - uses: npaun/md-gtfs-validator-action@main
        with:
          gtfs_path: ${{ env.GTFS_PATH }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Generate ZIP export'
          file_pattern: ${{ env.GTFS_PATH }}
